### ISSUE TITLE
Chosen car doesn't save

### ISSUE THREAD

**Issue by easybeat** [tronity/ioBroker.tronity#2]
**Describe the bug**  
I did enter the clientid and client secret and then when I press "Anmeldedaten prüfen" my car is shown. When I press "save/speichern" it looks like the information is stored. If I close the instance details and open it again, the car data is missing.

**To Reproduce**  
see in description

**Expected behavior**  
My car should be stored in settings

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/37217887/174494545-2d784727-e6d8-4801-b3a4-397995d88ed7.png)
after I reopen settings again:
![image](https://user-images.githubusercontent.com/37217887/174494576-89e8d844-e158-4112-966d-923249cc457c.png)

**Versions:**  
 - Adapter version: 1.1.1
 - JS-Controller version: 4.0.23
 - Node version: 14.19.2
 - Operating system: debian-linux

**Comment by sebastian-tronity** [comment]
This is normal. But it's still running.
